-- Pocketa ledger sync
-- GENERATED by `npm run sql` from the TypeScript source. Do not edit.
-- Paste into Supabase -> SQL Editor -> New query. Safe to run more than once.

-- Pocketa sync: one append-only table, isolated per user.
create table if not exists public.ops (
  id           text primary key,
  user_id      uuid not null references auth.users(id) on delete cascade,
  server_seq   bigserial not null,
  device_id    text not null,
  lamport      bigint not null,
  created_at   timestamptz not null,
  type         text not null,
  entity       text not null,
  entity_id    text not null,
  summary      text not null,
  changes      jsonb,
  snapshot     jsonb
);

create index if not exists ops_user_seq_idx on public.ops (user_id, server_seq);

alter table public.ops enable row level security;

-- Each account can only ever see and write its own rows.
--
-- Every policy is dropped first, so pasting this a second time updates the
-- rules instead of failing on "policy already exists".
drop policy if exists "read own ops" on public.ops;
create policy "read own ops"   on public.ops for select using (auth.uid() = user_id);

drop policy if exists "insert own ops" on public.ops;
create policy "insert own ops" on public.ops for insert with check (auth.uid() = user_id);

-- Update exists only so that re-sending a push whose acknowledgement was lost
-- is a no-op instead of a duplicate-key error. It is NOT a way to edit history,
-- so the row must still belong to the caller both before and after.
drop policy if exists "update own ops" on public.ops;
create policy "update own ops" on public.ops
  for update using (auth.uid() = user_id) with check (auth.uid() = user_id);

-- History is append-only: nothing may delete an op.
drop policy if exists "no deletes" on public.ops;
create policy "no deletes" on public.ops for delete using (false);

-- Enable Realtime so devices receive push notifications when new ops arrive.
-- This is safe: each device still filters by user_id via row-level security,
-- so a notification never exposes another user's data.
alter publication supabase_realtime add table public.ops;

-- ...and nothing may rewrite one either.
--
-- Without this, "append-only" was only half true: deletes were refused, but an
-- update could blank the contents of any row and leave the id in place. A
-- client that repeats a push sends the same values, so a genuine retry passes
-- this untouched; anything that actually changes what happened is rejected.
create or replace function public.ops_are_immutable()
returns trigger
language plpgsql
as $$
begin
  if new.id         is distinct from old.id
  or new.user_id    is distinct from old.user_id
  or new.device_id  is distinct from old.device_id
  or new.lamport    is distinct from old.lamport
  or new.created_at is distinct from old.created_at
  or new.type       is distinct from old.type
  or new.entity     is distinct from old.entity
  or new.entity_id  is distinct from old.entity_id
  or new.summary    is distinct from old.summary
  or new.changes    is distinct from old.changes
  or new.snapshot   is distinct from old.snapshot then
    raise exception 'ops are append-only: an entry cannot be rewritten once stored';
  end if;
  -- server_seq is assigned by the sequence and is never reissued on a repeat.
  new.server_seq := old.server_seq;
  return new;
end;
$$;

drop trigger if exists ops_immutable on public.ops;
create trigger ops_immutable
  before update on public.ops
  for each row execute function public.ops_are_immutable();

