/**
 * Writes the two schema scripts out as .sql files.
 *
 * The scripts live in TypeScript because the app prints them in Settings, and
 * one source means they can never drift from the code that expects them. But
 * pasting into a Postgres console is easier from a file than from a UI, so
 * these are generated on demand:
 *
 *   npm run sql
 *
 * The output is generated, never edited. Change the TypeScript.
 */
import { writeFileSync, mkdirSync, readFileSync } from 'node:fs';

const BACKSLASH = String.fromCharCode(92);
const BACKTICK = String.fromCharCode(96);

/** Pull an `export const NAME = <template literal>` out of a .ts file. */
function extract(file, name) {
  const source = readFileSync(file, 'utf8');
  const start = source.indexOf(`export const ${name} = ` + BACKTICK);
  if (start === -1) throw new Error(`${name} not found in ${file}`);
  const from = source.indexOf(BACKTICK, start) + 1;

  let i = from;
  while (i < source.length) {
    if (source[i] === BACKSLASH) {
      i += 2;
      continue;
    }
    if (source[i] === BACKTICK) break;
    i += 1;
  }
  if (i >= source.length) throw new Error(`${name} is not terminated in ${file}`);

  // Undo the escaping the template literal needed. Nothing here interpolates.
  return source
    .slice(from, i)
    .split(BACKSLASH + BACKTICK)
    .join(BACKTICK)
    .split(BACKSLASH + '$')
    .join('$')
    .split(BACKSLASH + BACKSLASH)
    .join(BACKSLASH);
}

mkdirSync('supabase', { recursive: true });

const banner = (what) =>
  `-- ${what}\n` +
  '-- GENERATED by `npm run sql` from the TypeScript source. Do not edit.\n' +
  '-- Paste into Supabase -> SQL Editor -> New query. Safe to run more than once.\n\n';

for (const [file, name, out, what] of [
  ['src/data/sync.ts', 'SCHEMA_SQL', 'supabase/1-ledger.sql', 'Pocketa ledger sync'],
  ['src/data/carpoolSchema.ts', 'CARPOOL_SCHEMA_SQL', 'supabase/2-carpool.sql', 'Pocketa shared carpool'],
]) {
  writeFileSync(out, banner(what) + extract(file, name).trimStart() + '\n');
  console.log(out);
}
